services:
  ui:
    build:
      dockerfile: Dockerfile
      context: .
      target: base
    command: ["npm", "run", "dev"]
    volumes:
      - ./:/app/
      - ./node_modules:/app/node_modules
    ports:
      - "3000:3000"